image: alpine/edge
packages:
  - rsync
  - hugo
sources:
  - https://git.sr.ht/~zetetic/svbn.me
secrets:
  - 31858fb0-d711-48f0-bb59-f09b63d345ca
tasks:
- build: |
    cd svbn.me
    hugo
- upload: |
    cd svbn.me
    echo "StrictHostKeyChecking=no" >> ~/.ssh/config
    rsync -rP public/ root@45.55.222.214:/var/lib/caddy/
