image: alpine/latest
packages:
  - hugo
oauth: pages.sr.ht/PAGES:RW
environment:
  site: stefan.vanburen.xyz
tasks:
  - build: |
      cd stefan.vanburen.xyz
      hugo --minify

      tar -C public -cvz . > site.tar.gz

  - upload: |
      cd stefan.vanburen.xyz

      # Only upload on the main branch.
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]
      then
        echo "Not on main branch, not publishing!"
        exit 0
      fi

      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
