# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD003/heading-style/header-style - Heading style
MD003:
  # Heading style
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  # List style - for best compatibility with Gemini
  style: "asterisk"

# MD010/no-hard-tabs - Hard tabs
MD010:
  # Include code blocks
  # I have a decent amount of `go` code that's written with hard tabs!
  code_blocks: false

# MD013/line-length - Line length
# I'll handle this myself, as I tend to like writing with Semantic Linefeeds,
# which don't always play nicely with line lengths.
MD013: false

# MD033/no-inline-html - Inline HTML
# I use inline HTML sparingly, when needed!
MD033: false
