repos:
  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        description: Runs stylelint on assets/*.css files.
        entry: npx stylelint
        language: system
        types: [css]
        files: ^assets/
        pass_filenames: true
      - id: htmltest
        name: htmltest
        description: Build site and run `htmltest -s` to check the generated site.
        entry: just htmltest
        language: system
        types_or: [markdown, html]
        pass_filenames: false
      - id: html-validate
        name: html-validate
        description: Build site and run `html-validate` to check the generated site.
        entry: just html-validate
        language: system
        types_or: [markdown, html]
        pass_filenames: false
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.5.0
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer
