repos:
- repo: local
  hooks:
  - id: stylelint
    name: stylelint
    description: Runs stylelint on assets/*.css files.
    entry: just lint
    language: system
    types: [css]
    files: ^assets/
    pass_filenames: false
