languageCode = "en-us"
title = "Stefan VanBuren"
baseurl = "https://stefan.vanburen.xyz/"
copyright = "©️ 2023 Stefan VanBuren"
description = "Stefan VanBuren's personal site."

disableKinds = ["taxonomy", "term"]

# for RSS
[params]
  mainSections = ["blog", "til"]

[minify]
  # minify output by default
  minifyOutput = true
  # don't minify xml files (RSS feeds)
  disableXML = true

[author]
  # for feeds
  name = "Stefan VanBuren"
  email = "stefan@vanburen.xyz"

[markup]
  [markup.highlight]
    style = "bw"
  [markup.goldmark]
    [markup.goldmark.renderer]
      # allows for inline HTML
      unsafe = true
