languageCode = "en-us"
title = "Stefan VanBuren"
baseurl = "https://svbn.me/"
theme = "hugo-theme-basic"
enableEmoji = true
enableRobotsTXT = true
description = "Stefan VanBuren's personal site."
pygmentsCodeFences = true
pygmentsStyle = "solarized-dark"
pygmentsUseClasses = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":robot:"

[[params.menu]]
  name = "blog"
  url = "blog/"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "rss"
  url = "index.xml"
