languageCode = "en-us"
title = "Stefan VanBuren"
baseurl = "http://svbn.me/"
theme = "hugo-xmin"

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "python"]

[[params.social]]
url = "https://github.com/svanburen"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/svbn_"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
