# https://gohugo.io/getting-started/configuration/
languageCode = "en-us"
title = "Stefan VanBuren"
baseURL = "https://stefan.vanburen.xyz/"
copyright = "©️ 2025 Stefan VanBuren"
enableGitInfo = true

disableKinds = ["taxonomy", "term"]

# for RSS
[params]
mainSections = ["blog", "til"]

[params.author]
# for feeds
name = "Stefan VanBuren"
email = "stefan@vanburen.xyz"

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark]
[markup.goldmark.renderer]
# allows for inline HTML
unsafe = true
