# https://gohugo.io/getting-started/configuration/
locale = "en-us"
title = "Stefan VanBuren"
baseURL = "https://stefan.vanburen.xyz/"
copyright = "©️ 2026 Stefan VanBuren"
enableGitInfo = true

disableKinds = ["taxonomy", "term"]
mainSections = ["blog", "til"]

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]
delimiter = "."

[outputFormats.Atom]
mediaType = "application/atom+xml"
baseName = "index"
isPlainText = true
rel = "alternate"

[outputs]
home = ["HTML", "Atom"]
section = ["HTML", "Atom"]
page = ["HTML"]

# Only affects `hugo server`; has no effect on the built output.
[server]
[[server.headers]]
for = "**/index.xml"
[server.headers.values]
Content-Type = "application/atom+xml; charset=utf-8"

[params.author]
# for feeds
name = "Stefan VanBuren"
email = "stefan@vanburen.xyz"

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
# allows for inline HTML
unsafe = true
