# https://gohugo.io/getting-started/configuration/
languageCode = "en-us"
title = "Stefan VanBuren"
baseurl = "https://stefan.vanburen.xyz/"
copyright = "©️ 2024 Stefan VanBuren"
description = "Stefan VanBuren's personal site."

disableKinds = ["taxonomy", "term"]

# for RSS
[params]
mainSections = ["blog", "til"]

[params.author]
# for feeds
name = "Stefan VanBuren"
email = "stefan@vanburen.xyz"

[markup]
[markup.highlight]
style = "bw"
[markup.goldmark]
[markup.goldmark.renderer]
# allows for inline HTML
unsafe = true
